# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the contents of the actions directory into the container
COPY actions/ /app/actions
COPY data/ /app/data

# Install any dependencies required for the action server
RUN pip install rasa-sdk

# Expose port 5055 to allow external connections
EXPOSE 5055

# Command to run the action server
CMD ["rasa", "run", "actions", "--cors", "*"]
